version: "2"

linters:
  enable:
    - errcheck
    - errname
    - exhaustive
    - godot
    - govet
    - ineffassign
    - lll
    - staticcheck
    - testpackage
    - unused
    - usestdlibvars
    - whitespace

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/nint8835/repo-archiver
